# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 20f8456ac27c149e5b736ad4dd5421d871fd2eca625fd38fd26799e360d7dfd8c2b40f97fc91404baf0dfb4d182ae56e884a769db119b7053943102fde14e1df

test:
  secret_key_base: f1ec147e81b990b8838c6f6be5e72e0ce199c83293706e3b4fd5af244100c7663c1de1af9e952c14f85417414a5bed950b957c04349b7c0c535e7029a836ccac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
